"""
Classify dictionary entries without mutating the source dictionary.

Input:
  assets/data/dictionary.compact.json

Outputs:
  assets/data/dictionary.tags.json
  docs/data/2026-06-21-dictionary-classification-report.md
"""
from __future__ import annotations

import json
from collections import Counter
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parent.parent
DICT = ROOT / "assets" / "data" / "dictionary.compact.json"
TAGS_OUT = ROOT / "assets" / "data" / "dictionary.tags.json"
REPORT_OUT = ROOT / "docs" / "data" / "2026-06-21-dictionary-classification-report.md"


CULTURAL_MARKERS: dict[str, tuple[str, ...]] = {
    "proverb": ("посл", "погов", "поговор"),
    "folklore": ("фольк", "фолькл"),
    "dzhangar": ("джангар",),
    "riddle": ("загад",),
}

DOMAIN_MARKERS: dict[str, tuple[str, ...]] = {
    "archaic": ("уст.", "устар", "редко"),
    "religion": ("рел.", "религ"),
    "zoology": ("зоол", "зоолог"),
    "botany": ("бот.", "ботан"),
    "anatomy": ("анат",),
}

GRAMMAR_MARKERS = (
    "род. п. от",
    "побуд. от",
    "страд. от",
    "и. д. от",
)

FUNCTION_MARKERS = (
    "частиц",
    "союз",
    "межд",
    "суффикс",
    "префикс",
    "аффикс",
    "оконч",
)

BEGINNER_BLOCKING_TAGS = {
    "archaic",
    "grammar_form",
    "function_word",
    "source_ruwikt",
}


def entry_blob(entry: dict[str, Any]) -> str:
    chunks = [entry.get("lemma") or "", entry.get("pos") or ""]
    for sense in entry.get("senses") or []:
        chunks.append(sense.get("def") or "")
        for example in sense.get("examples") or []:
            chunks.append(example.get("kal") or "")
            chunks.append(example.get("rus") or "")
    return "\n".join(chunks).lower()


def sense_count(entry: dict[str, Any]) -> int:
    return len(entry.get("senses") or [])


def example_count(entry: dict[str, Any]) -> int:
    return sum(len(sense.get("examples") or []) for sense in entry.get("senses") or [])


def classify_entry(entry: dict[str, Any]) -> list[str]:
    tags: set[str] = set()
    lemma = (entry.get("lemma") or "").strip()
    blob = entry_blob(entry)
    examples = example_count(entry)

    if len(lemma.split()) > 1:
        tags.add("multiword_lemma")
    if len(lemma) <= 2:
        tags.add("short_lemma")
    if entry.get("phonetic"):
        tags.add("has_phonetic")
    if entry.get("pos"):
        tags.add("has_pos")
    if entry.get("aliases"):
        tags.add("has_aliases")
    if examples:
        tags.add("has_examples")
    if entry.get("source") == "ruwikt":
        tags.add("source_ruwikt")

    if any(marker in blob for marker in GRAMMAR_MARKERS):
        tags.add("grammar_form")
    if any(marker in blob for marker in FUNCTION_MARKERS):
        tags.add("function_word")

    for tag, markers in CULTURAL_MARKERS.items():
        if any(marker in blob for marker in markers):
            tags.add(tag)
    if tags.intersection(CULTURAL_MARKERS):
        tags.add("cultural_candidate")

    for tag, markers in DOMAIN_MARKERS.items():
        if any(marker in blob for marker in markers):
            tags.add(tag)
    if tags.intersection({"religion", "zoology", "botany", "anatomy"}):
        tags.add("domain_term")

    if (
        "multiword_lemma" not in tags
        and not tags.intersection(BEGINNER_BLOCKING_TAGS)
        and sense_count(entry) <= 3
        and len(lemma) > 2
    ):
        tags.add("beginner_candidate")

    return sorted(tags)


def classify_entries(entries: list[dict[str, Any]]) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    records: list[dict[str, Any]] = []
    tag_counts: Counter[str] = Counter()
    sense_total = 0
    example_total = 0

    for entry in entries:
        tags = classify_entry(entry)
        tag_counts.update(tags)
        senses = sense_count(entry)
        examples = example_count(entry)
        sense_total += senses
        example_total += examples
        records.append(
            {
                "source_id": entry.get("id"),
                "lemma": entry.get("lemma"),
                "tags": tags,
                "senses": senses,
                "examples": examples,
            }
        )

    stats = {
        "entries": len(entries),
        "senses": sense_total,
        "examples": example_total,
        "tag_counts": dict(sorted(tag_counts.items())),
    }
    return records, stats


def render_report(stats: dict[str, Any]) -> str:
    tag_counts = stats["tag_counts"]
    lines = [
        "# Dictionary Classification Report",
        "",
        "Generated by `scripts/classify_dictionary.py`.",
        "",
        "## Summary",
        "",
        f"- entries: `{stats['entries']}`",
        f"- senses: `{stats['senses']}`",
        f"- examples: `{stats['examples']}`",
        f"- beginner candidates: `{tag_counts.get('beginner_candidate', 0)}`",
        f"- cultural candidates: `{tag_counts.get('cultural_candidate', 0)}`",
        f"- grammar forms: `{tag_counts.get('grammar_form', 0)}`",
        f"- multiword lemmas: `{tag_counts.get('multiword_lemma', 0)}`",
        "",
        "## Tag Counts",
        "",
    ]
    for tag, count in tag_counts.items():
        lines.append(f"- `{tag}`: `{count}`")
    lines.extend(
        [
            "",
            "## Notes",
            "",
            "- The classifier is heuristic and deterministic.",
            "- Raw dictionary entries are not modified.",
            "- Cultural tags come from visible markers such as `посл.`, `погов.`, `фольк.`, `Джангар`, and `загадка`.",
            "- `beginner_candidate` means usable for discovery/review pools, not automatically approved for lessons.",
            "",
        ]
    )
    return "\n".join(lines)


def write_outputs(root: Path, records: list[dict[str, Any]], stats: dict[str, Any]) -> None:
    data_out = root / "assets" / "data" / "dictionary.tags.json"
    report_out = root / "docs" / "data" / "2026-06-21-dictionary-classification-report.md"
    data_out.parent.mkdir(parents=True, exist_ok=True)
    report_out.parent.mkdir(parents=True, exist_ok=True)
    data_out.write_text(
        json.dumps(records, ensure_ascii=False, separators=(",", ":")),
        encoding="utf-8",
    )
    report_out.write_text(render_report(stats), encoding="utf-8")


def main() -> int:
    entries = json.loads(DICT.read_text(encoding="utf-8"))
    records, stats = classify_entries(entries)
    write_outputs(ROOT, records, stats)
    print(f"wrote {TAGS_OUT} ({len(records)} records)")
    print(f"wrote {REPORT_OUT}")
    for key in ("beginner_candidate", "cultural_candidate", "grammar_form", "multiword_lemma"):
        print(f"{key}: {stats['tag_counts'].get(key, 0)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
